[project]
name = "python-automation-projects-collection"
version = "0.1.0"
description = "A collection of python automation projects"
readme = "README.md"
authors = [
    { name = "Andrea Fiori", email = "info@andreafiori.net" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
python-automation-projects-collection = "python_automation_projects_collection:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
addopts = "-ra"

[dependency-groups]
dev = [
    "pytest",
]
